version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: irl_quest_db
      LANG: en_US.utf8
      LC_COLLATE: en_US.utf8
      LC_CTYPE: en_US.utf8
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c lc_messages='en_US.utf8'

volumes:
  postgres_data:
