package com.irlquest.app.ui.screens

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.lifecycle.viewmodel.compose.viewModel
import com.irlquest.app.ui.viewmodel.TaskViewModel
import com.irlquest.app.ui.viewmodel.AuthViewModel
import com.irlquest.app.data.network.dto.RagQuestGenerationResponse

@Composable
fun TasksScreen(onNavigateToQuests: () -> Unit, onLogout: () -> Unit = {}, viewModel: TaskViewModel = viewModel(), authViewModel: AuthViewModel = viewModel()) {
    val loading by viewModel.loading.collectAsState()
    val tasks by viewModel.tasks.collectAsState()
    val error by viewModel.error.collectAsState()
    val generated by viewModel.generatedQuest.collectAsState()

    val currentUser by authViewModel.currentUser.collectAsState()

    var showDialog by remember { mutableStateOf(false) }
    var newTitle by remember { mutableStateOf("") }
    var newDesc by remember { mutableStateOf("") }

    // Master inputs
    var masterTitle by remember { mutableStateOf("") }
    var masterDesc by remember { mutableStateOf("") }
    var masterPriority by remember { mutableStateOf("medium") }
    var masterDifficulty by remember { mutableStateOf(3) }
    var masterTagsText by remember { mutableStateOf("") }

    LaunchedEffect(Unit) {
        authViewModel.fetchMe()
        viewModel.loadTasks()
    }

    Column(modifier = Modifier.fillMaxSize().padding(16.dp)) {
        // Header row
        Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween, verticalAlignment = Alignment.CenterVertically) {
            Column {
                Text(text = "Tasks", style = MaterialTheme.typography.h5)
                if (currentUser != null) {
                    Text(text = "${currentUser!!.username} · ${currentUser!!.email}", style = MaterialTheme.typography.caption)
                }
            }
            Row {
                Button(onClick = { onNavigateToQuests() }) { Text("Quests") }
                Spacer(modifier = Modifier.width(8.dp))
                TextButton(onClick = { onLogout() }) { Text("Logout") }
            }
        }

        Spacer(modifier = Modifier.height(12.dp))

        // Quest Master
        Card(modifier = Modifier.fillMaxWidth()) {
            Column(modifier = Modifier.padding(12.dp)) {
                Text(text = "Quest Master", style = MaterialTheme.typography.h6)
                Spacer(modifier = Modifier.height(8.dp))
                OutlinedTextField(value = masterTitle, onValueChange = { masterTitle = it }, label = { Text("Task title") }, modifier = Modifier.fillMaxWidth())
                Spacer(modifier = Modifier.height(8.dp))
                OutlinedTextField(value = masterDesc, onValueChange = { masterDesc = it }, label = { Text("Task description (optional)") }, modifier = Modifier.fillMaxWidth(), maxLines = 3)
                Spacer(modifier = Modifier.height(8.dp))
                Row(verticalAlignment = Alignment.CenterVertically) {
                    // Priority simple selector
                    Text(text = "Priority:")
                    Spacer(modifier = Modifier.width(8.dp))
                    DropdownMenuWithOptions(selected = masterPriority, options = listOf("low","medium","high"), onSelect = { masterPriority = it })
                    Spacer(modifier = Modifier.width(16.dp))
                    // Difficulty selector (simple)
                    Text(text = "Difficulty:")
                    Spacer(modifier = Modifier.width(8.dp))
                    DropdownMenuWithOptions(selected = masterDifficulty.toString(), options = (1..5).map { it.toString() }, onSelect = { masterDifficulty = it.toInt() })
                }
                Spacer(modifier = Modifier.height(8.dp))
                OutlinedTextField(value = masterTagsText, onValueChange = { masterTagsText = it }, label = { Text("Tags (comma-separated, optional)") }, modifier = Modifier.fillMaxWidth())
                Spacer(modifier = Modifier.height(8.dp))
                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    Button(onClick = {
                        // If tags provided, split; else pass empty list and server will use ML
                        val tags = masterTagsText.split(",").map { it.trim() }.filter { it.isNotEmpty() }
                        viewModel.generateQuestFromTask(masterTitle, if (masterDesc.isBlank()) null else masterDesc, masterPriority, null, masterDifficulty, tags)
                    }, enabled = masterTitle.isNotBlank()) {
                        Text("Generate Quest")
                    }
                    OutlinedButton(onClick = {
                        masterTitle = ""
                        masterDesc = ""
                        masterTagsText = ""
                        masterDifficulty = 3
                        masterPriority = "medium"
                    }) { Text("Reset") }
                }
            }
        }

        Spacer(modifier = Modifier.height(12.dp))

        // If a quest was generated, show card with actions
        generated?.let { g ->
            GeneratedQuestCard(g,
                onSave = { viewModel.saveGeneratedQuest { /* optionally navigate */ } },
                onClose = { viewModel.clearGeneratedQuest() }
            )

            Spacer(modifier = Modifier.height(12.dp))
        }

        if (error != null) {
            Text(text = error ?: "", color = MaterialTheme.colors.error)
        }

        if (loading) {
            Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
                CircularProgressIndicator()
            }
            return@Column
        }

        LazyColumn(modifier = Modifier.fillMaxSize()) {
            items(tasks) { t ->
                // TaskDto не имеет поля `completed`; определим флаг завершения по status/completedAt
                val isCompleted = (t.completedAt != null) || t.status.equals("completed", ignoreCase = true)

                Card(modifier = Modifier.fillMaxWidth().padding(vertical = 4.dp)) {
                    Column(modifier = Modifier.padding(12.dp)) {
                        Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween, verticalAlignment = Alignment.CenterVertically) {
                            Column(modifier = Modifier.weight(1f)) {
                                Text(text = t.title, style = MaterialTheme.typography.subtitle1)
                                if (!t.description.isNullOrEmpty()) {
                                    Spacer(modifier = Modifier.height(4.dp))
                                    Text(text = t.description!!, style = MaterialTheme.typography.body2)
                                }

                                Spacer(modifier = Modifier.height(8.dp))
                                // attributes
                                Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                                    Text(text = "Priority: ${t.priority}")
                                    Text(text = "Difficulty: ${t.difficulty}")
                                    Text(text = "Tags: ${if (t.tags.isEmpty()) "—" else t.tags.joinToString(", ")}")
                                }
                            }
                            Row {
                                val doneText = if (isCompleted) "Undo" else "Done"
                                TextButton(onClick = { viewModel.updateTask(t.id, completed = !isCompleted) }) {
                                    Text(doneText)
                                }
                                Spacer(modifier = Modifier.width(4.dp))
                                TextButton(onClick = { viewModel.deleteTask(t.id) }) {
                                    Text("Delete")
                                }
                            }
                        }

                        Spacer(modifier = Modifier.height(8.dp))

                        // Action row: Predict attributes / Generate Quest
                        Row(horizontalArrangement = Arrangement.spacedBy(8.dp), verticalAlignment = Alignment.CenterVertically) {
                            OutlinedButton(onClick = { viewModel.classifyAndApplyAttributes(t.id, t.title, t.description) }) {
                                Text("Predict attributes")
                            }
                            Button(onClick = {
                                // Use existing attributes if present, else provide defaults
                                val priority = t.priority.ifBlank { "medium" }
                                val difficulty = if (t.difficulty <= 0) 3 else t.difficulty
                                val tags = if (t.tags.isEmpty()) emptyList() else t.tags
                                viewModel.generateQuestFromTask(t.title, if (t.description.isBlank()) null else t.description, priority, t.estimatedDuration, difficulty, tags)
                            }) {
                                Text("Generate Quest")
                            }
                        }
                    }
                }
            }
        }

        Spacer(modifier = Modifier.height(8.dp))

        FloatingActionButton(onClick = { showDialog = true }, modifier = Modifier.align(Alignment.End)) {
            Text(text = "+")
        }
    }

    if (showDialog) {
        AlertDialog(onDismissRequest = { showDialog = false }, title = { Text("Create task") }, text = {
            Column {
                OutlinedTextField(value = newTitle, onValueChange = { newTitle = it }, label = { Text("Title") })
                Spacer(modifier = Modifier.height(8.dp))
                OutlinedTextField(value = newDesc, onValueChange = { newDesc = it }, label = { Text("Description") })
            }
        }, confirmButton = {
            TextButton(onClick = {
                viewModel.createTask(newTitle, if (newDesc.isBlank()) null else newDesc) {
                    showDialog = false
                    newTitle = ""
                    newDesc = ""
                }
            }) { Text("Create") }
        }, dismissButton = {
            TextButton(onClick = { showDialog = false }) { Text("Cancel") }
        })
    }
}

// --- helper composables ---
@Composable
private fun DropdownMenuWithOptions(selected: String, options: List<String>, onSelect: (String) -> Unit) {
    var expanded by remember { mutableStateOf(false) }
    Box {
        OutlinedButton(onClick = { expanded = true }) {
            Text(selected)
        }
        DropdownMenu(expanded = expanded, onDismissRequest = { expanded = false }) {
            options.forEach { opt ->
                DropdownMenuItem(onClick = { onSelect(opt); expanded = false }) {
                    Text(opt)
                }
            }
        }
    }
}

@Composable
private fun GeneratedQuestCard(g: RagQuestGenerationResponse, onSave: () -> Unit, onClose: () -> Unit) {
    Card(modifier = Modifier.fillMaxWidth()) {
        Column(modifier = Modifier.padding(12.dp)) {
            Text(text = g.title, style = MaterialTheme.typography.h6)
            Spacer(modifier = Modifier.height(8.dp))
            Text(text = g.description, style = MaterialTheme.typography.body1)
            Spacer(modifier = Modifier.height(8.dp))
            Text(text = "Tasks:")
            g.tasks.forEach { task ->
                Text(text = "• ${task.title} — ${task.description}")
            }
            Spacer(modifier = Modifier.height(8.dp))
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                Button(onClick = onSave) { Text("Save as Quest") }
                OutlinedButton(onClick = onClose) { Text("Close") }
            }
        }
    }
}
